-- =========================================================
-- V20__create_account_job_schedules.sql
-- NO-OP (intencional)
-- =========================================================
-- Contexto:
-- - A tabela account_job_schedules já é criada na:
--     V15__create_table_account_job_schedules.sql
--
-- - Este projeto SEMPRE executa:
--     DROP DATABASE + Flyway migrate
--
-- Decisão arquitetural:
-- - Existe uma única fonte de verdade para essa tabela (V15)
-- - Evitamos duplicidade semântica no histórico de migrations
-- - Evitamos divergência de DDL (tamanhos, índices, constraints)
--
-- IMPORTANTE:
-- - NÃO recriar a tabela aqui
-- - NÃO alterar colunas aqui
-- - NÃO recriar índices aqui
--
-- Esta migration existe apenas para manter a sequência do Flyway.
-- =========================================================

SELECT 1;