-- V1__create_table_tenant_users.sql

CREATE TABLE IF NOT EXISTS tenant_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_origin VARCHAR(20) NOT NULL DEFAULT 'ADMIN',

    account_id BIGINT NOT NULL,

    name VARCHAR(100) NOT NULL,

    -- ✅ email é a identidade de login
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,

    role VARCHAR(50) NOT NULL,

    suspended_by_account BOOLEAN NOT NULL DEFAULT FALSE,
    suspended_by_admin  BOOLEAN NOT NULL DEFAULT FALSE,

    last_login TIMESTAMP,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    must_change_password BOOLEAN NOT NULL DEFAULT false,
    password_changed_at TIMESTAMP,
    password_reset_token VARCHAR(255),
    password_reset_expires TIMESTAMP,

    phone VARCHAR(20),
    avatar_url VARCHAR(500),

    timezone VARCHAR(60) NOT NULL DEFAULT 'America/Sao_Paulo',
    locale VARCHAR(20) NOT NULL DEFAULT 'pt_BR',

    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,

    deleted_by BIGINT,

    created_by_username VARCHAR(120),
    updated_by_username VARCHAR(120),
    deleted_by_username VARCHAR(120),

    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_tenant_user_origin CHECK (user_origin IN ('BUILT_IN', 'ADMIN', 'API')),

    -- ✅ email único por account dentro do schema do tenant (mesmo que o schema tenha só 1 account)
    CONSTRAINT uk_tenant_users_email_account UNIQUE (email, account_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_users_account_id ON tenant_users(account_id);
CREATE INDEX IF NOT EXISTS idx_tenant_users_deleted ON tenant_users(deleted) WHERE deleted = false;
