package brito.com.multitenancy001.tenant.inventory.app;

import java.math.BigDecimal;
import java.util.UUID;

import org.springframework.stereotype.Service;

import brito.com.multitenancy001.infrastructure.persistence.tx.TenantTx;
import brito.com.multitenancy001.shared.api.error.ApiErrorCode;
import brito.com.multitenancy001.shared.kernel.error.ApiException;
import brito.com.multitenancy001.tenant.inventory.app.command.AdjustInventoryCommand;
import brito.com.multitenancy001.tenant.inventory.domain.InventoryItem;
import brito.com.multitenancy001.tenant.inventory.domain.InventoryMovementType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * Service de integração entre Inventory e Sales.
 *
 * <p>Responsabilidades:</p>
 * <ul>
 *   <li>Consumir estoque por venda.</li>
 *   <li>Restaurar estoque por cancelamento/reversão de venda.</li>
 *   <li>Montar commands padronizados para o fluxo de adjustment.</li>
 * </ul>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class TenantInventorySalesIntegrationService {

    private final TenantInventoryQueryService tenantInventoryQueryService;
    private final TenantInventoryAdjustmentService tenantInventoryAdjustmentService;

    /**
     * Consome estoque por item de venda.
     *
     * @param saleId id da venda
     * @param productId id do produto
     * @param quantity quantidade positiva a ser consumida
     * @return inventory atualizado
     */
    @TenantTx
    public InventoryItem consumeStockForSale(UUID saleId, UUID productId, BigDecimal quantity) {
        if (saleId == null) {
            throw new ApiException(ApiErrorCode.SALE_NOT_FOUND, "saleId is required", 400);
        }
        if (productId == null) {
            throw new ApiException(ApiErrorCode.PRODUCT_ID_REQUIRED, "productId is required", 400);
        }
        if (quantity == null || quantity.signum() <= 0) {
            throw new ApiException(ApiErrorCode.INVALID_REQUEST, "sale item quantity must be positive", 400);
        }

        log.info(
                "INVENTORY_CONSUME_FOR_SALE_START | saleId={} | productId={} | requestedQuantity={}",
                saleId,
                productId,
                quantity
        );

        InventoryItem before = tenantInventoryQueryService.getOrCreateInventory(productId);

        log.debug(
                "INVENTORY_CONSUME_FOR_SALE_BEFORE | saleId={} | productId={} | available={} | reserved={}",
                saleId,
                productId,
                before.getQuantityAvailable(),
                before.getQuantityReserved()
        );

        AdjustInventoryCommand command = AdjustInventoryCommand.builder()
                .productId(productId)
                .quantity(quantity.negate())
                .movementType(InventoryMovementType.OUTBOUND)
                .referenceType("SALE")
                .referenceId(String.valueOf(saleId))
                .notes("Automatic outbound movement generated by sale")
                .build();

        InventoryItem item = tenantInventoryAdjustmentService.adjustInventory(command);

        log.info(
                "INVENTORY_CONSUME_FOR_SALE_FINISH | saleId={} | productId={} | consumed={} | newAvailable={} | newReserved={}",
                saleId,
                productId,
                quantity,
                item.getQuantityAvailable(),
                item.getQuantityReserved()
        );

        return item;
    }

    /**
     * Devolve estoque anteriormente consumido por venda.
     *
     * @param saleId id da venda
     * @param productId id do produto
     * @param quantity quantidade positiva a devolver
     * @return inventory atualizado
     */
    @TenantTx
    public InventoryItem restoreStockFromSale(UUID saleId, UUID productId, BigDecimal quantity) {
        if (saleId == null) {
            throw new ApiException(ApiErrorCode.SALE_NOT_FOUND, "saleId is required", 400);
        }
        if (productId == null) {
            throw new ApiException(ApiErrorCode.PRODUCT_ID_REQUIRED, "productId is required", 400);
        }
        if (quantity == null || quantity.signum() <= 0) {
            throw new ApiException(ApiErrorCode.INVALID_REQUEST, "restore quantity must be positive", 400);
        }

        log.info(
                "INVENTORY_RESTORE_FROM_SALE_START | saleId={} | productId={} | quantity={}",
                saleId,
                productId,
                quantity
        );

        InventoryItem before = tenantInventoryQueryService.getOrCreateInventory(productId);

        log.debug(
                "INVENTORY_RESTORE_FROM_SALE_BEFORE | saleId={} | productId={} | available={} | reserved={}",
                saleId,
                productId,
                before.getQuantityAvailable(),
                before.getQuantityReserved()
        );

        AdjustInventoryCommand command = AdjustInventoryCommand.builder()
                .productId(productId)
                .quantity(quantity)
                .movementType(InventoryMovementType.RETURN)
                .referenceType("SALE_CANCEL")
                .referenceId(String.valueOf(saleId))
                .notes("Automatic stock restoration generated by sale cancellation/reversal")
                .build();

        InventoryItem item = tenantInventoryAdjustmentService.adjustInventory(command);

        log.info(
                "INVENTORY_RESTORE_FROM_SALE_FINISH | saleId={} | productId={} | restored={} | newAvailable={} | newReserved={}",
                saleId,
                productId,
                quantity,
                item.getQuantityAvailable(),
                item.getQuantityReserved()
        );

        return item;
    }
}